import type { Metadata } from "next";
import { Inter } from "next/font/google";
import WrapperLayout from "../components/wrapperLayout";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "money manager",
  description: "Generated by money manager",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WrapperLayout>{children}</WrapperLayout>
      </body>
    </html>
  );
}
